/* Scintilla source code edit control
 * Partitioning.c — C translation of scintilla/src/Partitioning.h (impl)
 *
 * The implementation is generated by including pt_impl.h twice,
 * once per concrete element type.
 */

#include "Partitioning.h"   /* brings in the struct typedefs via pt_tpl.h */

/* ── Name-mangling helpers ─────────────────────────────────────────── */
#define _PT_CAT2(a,b) a##b
#define _PT_CAT(a,b)  _PT_CAT2(a,b)
#define PT_STRUCT  _PT_CAT(Partitioning_, PT_SUFFIX)
#define PT_FN(fn)  _PT_CAT(_PT_CAT(Partitioning_, PT_SUFFIX), _PT_CAT(_, fn))

/* ── Instantiation 1: Partitioning_Int (T = int) ───────────────────── */
#define PT_T      int
#define PT_SUFFIX Int
#define PT_SV     SplitVector_Int
#include "pt_impl.h"
#undef PT_T
#undef PT_SUFFIX
#undef PT_SV

/* ── Instantiation 2: Partitioning_PD (T = ptrdiff_t) ──────────────── */
#define PT_T      ptrdiff_t
#define PT_SUFFIX PD
#define PT_SV     SplitVector_PD
#include "pt_impl.h"
#undef PT_T
#undef PT_SUFFIX
#undef PT_SV

#undef _PT_CAT2
#undef _PT_CAT
#undef PT_STRUCT
#undef PT_FN
