/* Scintilla source code edit control
 * SplitVector.c — C translation of scintilla/src/SplitVector.h
 *
 * The implementation is generated by including sv_impl.h three times,
 * once per concrete element type, with SV_T / SV_SUFFIX / SV_ZERO set.
 *
 * Each inclusion expands into a full set of static-helper + public function
 * bodies for that concrete SplitVector_SV_SUFFIX type.  The private GapTo
 * and RoomFor helpers are declared 'static' inside sv_impl.h so they do
 * not pollute the link namespace.
 */

#include "SplitVector.h"   /* brings in the struct typedefs via sv_tpl.h */

/* ── Instantiation 1: SplitVector_Char (T = char) ───────────────────── */
#define SV_T       char
#define SV_SUFFIX  Char
#define SV_ZERO    '\0'
#include "sv_impl.h"
#undef SV_T
#undef SV_SUFFIX
#undef SV_ZERO

/* ── Instantiation 2: SplitVector_Int (T = int) ─────────────────────── */
#define SV_T       int
#define SV_SUFFIX  Int
#define SV_ZERO    0
#include "sv_impl.h"
#undef SV_T
#undef SV_SUFFIX
#undef SV_ZERO

/* ── Instantiation 3: SplitVector_PD (T = ptrdiff_t) ───────────────── */
#define SV_T       ptrdiff_t
#define SV_SUFFIX  PD
#define SV_ZERO    0
#include "sv_impl.h"
#undef SV_T
#undef SV_SUFFIX
#undef SV_ZERO
